### ISSUE TITLE
Travis CI build fails

### ISSUE THREAD

**Issue by Ritzlgrmft** [Ritzlgrmft/ionic-logging-service#2]
https://travis-ci.org/Ritzlgrmft/ionic-logging-service/builds/205330556:

```
$ npm test
> ionic-logging-service@0.0.0-development test /home/travis/build/Ritzlgrmft/ionic-logging-service
> npm run compile && npm run lint && npm run karma-once
> ionic-logging-service@0.0.0-development compile /home/travis/build/Ritzlgrmft/ionic-logging-service
> ngc
Error: Error at /home/travis/build/Ritzlgrmft/ionic-logging-service/node_modules/@types/jasmine/index.d.ts:39:38: A parameter initializer is only allowed in a function or constructor implementation.
Error at /home/travis/build/Ritzlgrmft/ionic-logging-service/node_modules/@types/jasmine/index.d.ts:39:46: Cannot find name 'keyof'.
Error at /home/travis/build/Ritzlgrmft/ionic-logging-service/node_modules/@types/jasmine/index.d.ts:39:52: '=' expected.
    at check (/home/travis/build/Ritzlgrmft/ionic-logging-service/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/home/travis/build/Ritzlgrmft/ionic-logging-service/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /home/travis/build/Ritzlgrmft/ionic-logging-service/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
```

**Comment by Ritzlgrmft** [comment]
`@types/jasmine` must be fixed to version `2.5.41`
